In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("house_data.csv")
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   str
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   str
 15  city           4600 non-null   str
 16  statezip       4600 non-null   str
 17  country        4600 non-null   str
dtypes: float64(4), int64(9), str(5)
memory usage: 647.0 KB

In [2]:
data.head(20)
data.tail(20)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
4580,2014-07-07 00:00:00,282508.888889,3.0,1.00,1560,7552,1.0,0,0,4,910,650,1948,0,228 NE 174th St,Shoreline,WA 98155,USA
4581,2014-07-07 00:00:00,473200.000000,3.0,1.50,1740,4200,1.5,0,0,4,1640,100,1920,0,6714 4th Ave NW,Seattle,WA 98117,USA
4582,2014-07-07 00:00:00,406062.500000,2.0,1.00,1290,4650,1.0,0,0,4,1290,0,1906,1990,312 NE 81st St,Seattle,WA 98115,USA
4583,2014-07-07 00:00:00,282766.666667,4.0,2.00,1700,8640,1.0,0,0,3,850,850,1955,2010,3706 140th Ave SE,Bellevue,WA 98006,USA
4584,2014-07-07 00:00:00,486445.833333,3.0,1.75,1880,10032,1.0,0,0,4,1880,0,1984,0,13345 SE 55th Pl,Bellevue,WA 98006,USA
4585,2014-07-07 00:00:00,486895.000000,3.0,1.00,1890,3330,1.5,0,0,4,1390,500,1901,0,4324 Dayton Ave N,Seattle,WA 98103,USA
4586,2014-07-07 00:00:00,430277.777778,3.0,2.25,1620,1075,3.0,0,0,3,1540,80,2009,0,972 4th Ave NE,Issaquah,WA 98029,USA
4587,2014-07-08 00:00:00,229629.500000,2.0,1.00,770,8149,1.0,0,0,3,770,0,1948,1994,16040 28th Ave NE,Shoreline,WA 98155,USA
4588,2014-07-08 00:00:00,0.000000,4.0,2.25,2890,18226,3.0,1,4,3,2890,0,1984,0,3227-3399 Mountain View Ave N,Renton,WA 98056,USA
4589,2014-07-08 00:00:00,182805.000000,3.0,1.00,1040,8892,1.0,0,0,4,800,240,1958,1972,1028 SW 307th St,Federal Way,WA 98023,USA
4590,2014-07-08 00:00:00,380680.555556,4.0,2.50,2620,8331,2.0,0,0,3,2620,0,1991,0,13602 SE 186th Pl,Renton,WA 98058,USA
4591,2014-07-08 00:00:00,396166.666667,3.0,1.75,1880,5752,1.0,0,0,4,940,940,1945,0,3529 SW Webster St,Seattle,WA 98126,USA
4592,2014-07-08 00:00:00,252980.000000,4.0,2.50,2530,8169,2.0,0,0,3,2530,0,1993,0,37654 18th Pl S,Federal Way,WA 98003,USA
4593,2014-07-08 00:00:00,289373.307692,3.0,2.50,2538,4600,2.0,0,0,3,2538,0,2013,1923,5703 Charlotte Ave SE,Auburn,WA 98092,USA
4594,2014-07-09 00:00:00,210614.285714,3.0,2.50,1610,7223,2.0,0,0,3,1610,0,1994,0,26306 127th Ave SE,Kent,WA 98030,USA
4595,2014-07-09 00:00:00,308166.666667,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,534333.333333,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,416904.166667,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,203400.000000,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,220600.000000,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [3]:
data.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [4]:
data.head(20)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA
5,2014-05-02 00:00:00,490000.0,2.0,1.00,880,6380,1.0,0,0,3,880,0,1938,1994,522 NE 88th St,Seattle,WA 98115,USA
6,2014-05-02 00:00:00,335000.0,2.0,2.00,1350,2560,1.0,0,0,3,1350,0,1976,0,2616 174th Ave NE,Redmond,WA 98052,USA
7,2014-05-02 00:00:00,482000.0,4.0,2.50,2710,35868,2.0,0,0,3,2710,0,1989,0,23762 SE 253rd Pl,Maple Valley,WA 98038,USA
8,2014-05-02 00:00:00,452500.0,3.0,2.50,2430,88426,1.0,0,0,4,1570,860,1985,0,46611-46625 SE 129th St,North Bend,WA 98045,USA
9,2014-05-02 00:00:00,640000.0,4.0,2.00,1520,6200,1.5,0,0,3,1520,0,1945,2010,6811 55th Ave NE,Seattle,WA 98115,USA
10,2014-05-02 00:00:00,463000.0,3.0,1.75,1710,7320,1.0,0,0,3,1710,0,1948,1994,Burke-Gilman Trail,Lake Forest Park,WA 98155,USA
11,2014-05-02 00:00:00,1400000.0,4.0,2.50,2920,4000,1.5,0,0,5,1910,1010,1909,1988,3838-4098 44th Ave NE,Seattle,WA 98105,USA
12,2014-05-02 00:00:00,588500.0,3.0,1.75,2330,14892,1.0,0,0,3,1970,360,1980,0,1833 220th Pl NE,Sammamish,WA 98074,USA
13,2014-05-02 00:00:00,365000.0,3.0,1.00,1090,6435,1.0,0,0,4,1090,0,1955,2009,2504 SW Portland Ct,Seattle,WA 98106,USA
14,2014-05-02 00:00:00,1200000.0,5.0,2.75,2910,9480,1.5,0,0,3,2910,0,1939,1969,3534 46th Ave NE,Seattle,WA 98105,USA
15,2014-05-02 00:00:00,242500.0,3.0,1.50,1200,9720,1.0,0,0,4,1200,0,1965,0,14034 SE 201st St,Kent,WA 98042,USA
16,2014-05-02 00:00:00,419000.0,3.0,1.50,1570,6700,1.0,0,0,4,1570,0,1956,0,15424 SE 9th St,Bellevue,WA 98007,USA
17,2014-05-02 00:00:00,367500.0,4.0,3.00,3110,7231,2.0,0,0,3,3110,0,1997,0,11224 SE 306th Pl,Auburn,WA 98092,USA
18,2014-05-02 00:00:00,257950.0,3.0,1.75,1370,5858,1.0,0,0,3,1370,0,1987,2000,1605 S 245th Pl,Des Moines,WA 98198,USA
19,2014-05-02 00:00:00,275000.0,3.0,1.50,1180,10277,1.0,0,0,3,1180,0,1983,2009,12425 415th Ave SE,North Bend,WA 98045,USA

In [5]:
data["city"].value_counts()

city
Seattle                1573
Renton                  293
Bellevue                286
Redmond                 235
Kirkland                187
Issaquah                187
Kent                    185
Auburn                  176
Sammamish               175
Federal Way             148
Shoreline               123
Woodinville             115
Maple Valley             96
Mercer Island            86
Burien                   74
Snoqualmie               71
Kenmore                  66
Des Moines               58
North Bend               50
Covington                43
Duvall                   42
Lake Forest Park         36
Bothell                  33
Newcastle                33
Tukwila                  29
Vashon                   29
SeaTac                   29
Enumclaw                 28
Carnation                22
Normandy Park            18
Fall City                11
Clyde Hill               11
Medina                   11
Black Diamond             9
Ravensdale                7
Pacific                   6
Algona                    5
Yarrow Point              4
Skykomish                 3
Preston                   2
Milton                    2
Inglewood-Finn Hill       1
Snoqualmie Pass           1
Beaux Arts Village        1
Name: count, dtype: int64

In [6]:
data["yr_built"].value_counts()

yr_built
2006    111
2005    104
2007     93
2004     92
1978     90
       ...
1915      6
1935      6
1933      5
1934      4
1936      3
Name: count, Length: 115, dtype: int64

In [7]:
data.dtypes

date                 str
price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
street               str
city                 str
statezip             str
country              str
dtype: object

In [8]:
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   str
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   str
 15  city           4600 non-null   str
 16  statezip       4600 non-null   str
 17  country        4600 non-null   str
dtypes: float64(4), int64(9), str(5)
memory usage: 647.0 KB
None

In [9]:
# Remove duplicates
data = data.drop_duplicates()

# Remove zero-price rows
data = data[data["price"] > 0]

# Convert date
data["date"] = pd.to_datetime(data["date"])
data["year"] = data["date"].dt.year
data["month"] = data["date"].dt.month
data.drop("date", axis=1, inplace=True)

# Remove unnecessary columns
data.drop(["street", "country"], axis=1, inplace=True)

In [10]:
data.dtypes

price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
city                 str
statezip             str
year               int32
month              int32
dtype: object

In [11]:
data.drop(columns=["statezip"], inplace=True)

In [12]:
data.drop(columns=["city"], inplace=True)

In [13]:
data.dtypes

price            float64
bedrooms         float64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
year               int32
month              int32
dtype: object

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Features and Target
X = data.drop("price", axis=1)
y = data["price"]

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Create StandardScaler object
scaler = StandardScaler()

# Fit on training data and transform
X_train = scaler.fit_transform(X_train)

# Transform test data
X_test = scaler.transform(X_test)

# Check shapes
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (3640, 14)
X_test : (911, 14)
y_train: (3640,)
y_test : (911,)

In [15]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,10))
sns.heatmap(X,annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

from sklearn.metrics import r2_score

# Dictionary of models
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "KNN": KNeighborsRegressor(),
    "SVR": SVR()
}

# Train and evaluate
results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    score = r2_score(y_test, y_pred)

    results.append({
        "Model": name,
        "R2 Score": score
    })

# Display results
import pandas as pd

results = pd.DataFrame(results)
results = results.sort_values(by="R2 Score", ascending=False)

print(results)

               Model  R2 Score
0  Linear Regression  0.597188
2      Random Forest  0.515526
3                KNN  0.246641
1      Decision Tree  0.052528
4                SVR -0.056594

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
import joblib

# Create model
rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42
)

# Train model
rf.fit(X_train, y_train)

# Predict
y_pred = rf.predict(X_test)

# Accuracy
score = r2_score(y_test, y_pred)
print("R2 Score:", score)

R2 Score: 0.5170905594401174

In [ ]:
import joblib

joblib.dump(rf, "house_price_rf.pkl")

print("Model Saved Successfully!")

Model Saved Successfully!